version: '3.6'
services:
  aps_parser:
    container_name: aps_parser
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      #CONFIG SERVER
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: aps_parser
      M_TOKEN: ${M_TOKEN}
      #END CONFIG SERVER

#    ports:
#      - 82:81
networks:
  dc-net:
    external: true